services:
  backend:
    build: backend

  frontend:
    build:
      context: frontend
      target: "dev"

  web:
    build: nginx
    environment:
      - FRONTEND_HOST=frontend
      - BACKEND_HOST=backend
    ports:
      - "80:80"
      - "443:443"
