services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  backend:
    build:
      context: backend
      target: "base"
    env_file:
      - .env
    environment:
      - EXTERNAL_HOST=$EXTERNAL_HOST

  frontend:
    build:
      context: frontend
      target: "dev"

  web:
    build: nginx
    environment:
      - FRONTEND_HOST=frontend
      - BACKEND_HOST=backend
    ports:
      - "80:80"
      - "443:443"
