version: "3.8"

services:
  dev-backend:
    extends:
      file: docker-compose.yml
      service: backend
    ports:
      - "80:80"
    entrypoint: "python manage.py runserver 0.0.0.0:80"

  dev-frontend:
    build:
      context: "./frontend"
      target: "prerelease"
    environment:
      - HOSTNAME=dev-frontend
    ports:
      - "3000:3000"
    entrypoint: "bun run dev"